name: CI

on:
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install And Build
      run: |+
        cd website
        npm install
        npm run build
